name: Hnd checker
on: 
  workflow_dispatch:
jobs: 
  test: 
    defaults: 
      run: 
        working-directory: .
    name: "Run tests"
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with: 
          node-version: "18"
      - 
        name: "Install newman"
        run: "npm install -g newman"
      - 
        name: "Run tests"
        run: "newman run Hnd.postman_collection.json"
        
